### ISSUE TITLE
3D trajectory planning

### ISSUE THREAD

**Issue by Changliu52** [sikang/mpl_ros#11]
Thank you so much for sharing the code. The testing launches works amazing!
It seems to me that all the testing examples are with 2D trajectory planing, I am wondering if you could suggest some guideline to plan a 3d trajectory, as shown in the 3D voxel map figure in the readme?

Thank you in advance.
Chang

**Comment by sikang** [comment]
Hi Chang,

No problem! You can take a look at this script: mpl_test_node/launch/map_planner_node/test.launch.skir
(just remove the '.skir' and roslaunch it should work).

**Comment by Changliu52** [comment]
Awesome. Perfect!
Thank you Sikang!
